// }else if (menuutama==2)
// var konfirmasi2 = true
// var totalbelanja =0
// while(komfirmasi2){
//     var listbarang=prompt('menu belanja :\n1.ayam RP.10000\n2.Salmon Rp.20.000\n3.kalkun Rp.30.000')
//     var harga = 0
//     if(listbarang==1){
//         harga=10000
//     }else if(listbarang==2){
//      harga=20000
//     }else if(listbarang==3){
//         harga==30000
//     }
//     var qty = parseint( (prompt('mau belanja berapa kilo'))
//     var totalbelanja = qty * harga
//     konfirmasi2=confirm('mau belanja lagi ga?')
//     if(totalbelanja){
//         alert('total belanja anda adalah Rp.' + totalbelanja)
//     }else{
//     alert=('anda miskin')
//     }

// }else if (menuutama==3){    

// }
// }

